### ISSUE TITLE
Define DAC API method for initializing an activator

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#103]
Define DAC API method for onboarding an activator

This DAC method will get called when an activator is imported via the Eagle console. See #99 

Parameters required:
* Activator id
* Activator name
* Activator git repo URL

**Comment by Salles-FA** [comment]
This issue is part of a Story in which the diagrams are described here:

 -  https://github.com/tranquilitybase-io/TranquilityBase/issues/47

**Comment by aivogft** [comment]
`example:
        {
          repo: {
            activatorName: 'tb-gcp-hpc-activator',
            repoURL: '<some git url>',
            tagName: '<version>'
          }
        }`
