### ISSUE TITLE
Provide a method to change behaviour of DAC mock

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#104]
It should be possible to change the values the DAC mock returns in order to test how Eagle/Houston handles different responses
For example whether a task returns SUCCESS or FAILURE.

Possible ways to do this:
* through a value on the JSON input
* add an extra api method for setting mock properties
* using [OpenApi Mock](https://github.com/muonsoft/openapi-mock)

**Comment by karwootang-gft** [comment]
Have you looked at query parameters?
https://swagger.io/docs/specification/describing-parameters/#query-parameters

You can pass in optional query parameters to any of the CRUD operations, we use them in the HS. 
e.g.
/products?color=blue&color=green,
