### ISSUE TITLE
[FEATURE]  Houston/DB can become out of synch with the DaC, especially in the DEV env 

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-gcp-dac#110]
I think it would be useful to get a fresh of existing deployed resources from the DaC to populate/re-populate the database.
The current database doesn't keep it's state when stopped/restarted and there can be multiple instances running locally for developer/user. The alternates would be, to delete the deployed resources and re-deploy them which is more costly in terms of time. Or, have a single DB CloudSQL where the data is persisted.

**Comment by sunderhill-gft** [comment]
In a deployed landing zone this is not  an issue.
