### ISSUE TITLE
Check Jenkins job for completion and output

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#113]
For a Jenkins Deploy Activator job
* Poll the job in Jenkins and check it has completed
* Retrieve any output (success or failure) and return as a response to the Houston service

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/27

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/49
