### ISSUE TITLE
When Deploy All is clicked in Eagle, deploy Solution and Activators in sequence in DAC

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#116]
When Deploy All is clicked in Eagle, deploy Solution and Activators in sequence in DAC.

Activator deployments will need to use outputs from the solution deployment. e.g. project ids

Use Celery Chains or similar to create dependencies between tasks. 

Details TBD

**Comment by Salles-FA** [comment]
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/207
