### ISSUE TITLE
End Point to GET Cloud Identity Groups for a given user account

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-gcp-dac#123]
During login Houston will fetch form this End Point to validate if the user belongs to valid Eagle Console groups.

**Comment by karwootang-gft** [comment]
[https://github.com/tranquilitybase-io/tb-houston-service/issues/342](url)

**Comment by sunderhill-gft** [comment]
Command to get iam policy for a particular user account
`gcloud beta iam service-accounts get-iam-policy user@company.com`

Error message for currenty used service account (from landing zone)
`ERROR: (gcloud.beta.iam.service-accounts.get-iam-policy) PERMISSION_DENIED: Permission iam.serviceAccounts.getIamPolicy is required to perform this operation on service account projects/-/serviceAccounts/user@company.com.`
