### ISSUE TITLE
Permission each User that belongs to the Solution's Team for the non-prod Projects

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#13]
For each non-prod environment project, add permissions for the solution's team.
if one of the environments listed in the json input is 'Production' then the team will not be added for this environment's project.
They will be added for all other environments's project and also the workspace project.

The permissions added should allow the team members to access resources within the project but not change them. Use the role 'roles/viewer' and not 'roles/editor'
NB 'roles/owner' CANNOT be set for a user from the command line for a project. It has to be set from the Google console.

See https://cloud.google.com/iam/docs/understanding-roles#project-roles, https://cloud.google.com/sdk/gcloud/reference/projects/add-iam-policy-binding

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/20
