### ISSUE TITLE
Support refactoring of 'envs' field for solution and applications

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-gcp-dac#131]
Houston service will be sending object instead of string for environment

**Comment by sunderhill-gft** [comment]
example input 
{
    "description": "New Application",
    "mandatoryVariables": [],
    "id": 7,
    "deploymentEnvironment": {
        "sharedVPCProjectId": "shared_vpc_host_project",
        "id": 2,
        "name": "Production"
    },
    "optionalVariables": [],
    "workspaceProjectId": "workspace-h08aez-ksjs726s",
    "lastUpdated": "2020-08-18 09:19:31",
    "activatorGitUrl": "",
    "solutionId": 11,
    "name": "New Application",
    "deploymentProjectId": "production-h08aez-ksjs726s"
}

**Comment by sunderhill-gft** [comment]
example input for solution
{
    "isActive": true,
    "description": "test",
    "ci": "Bamboo",
    "id": 11,
    "ciId": 1,
    "cd": "Central",
    "businessUnit": "Modern Apps",
    "sourceControl": "BitBucket",
    "team": {
        "description": "All Developers",
        "isActive": true,
        "teamMembers": [
            {
                "id": 2,
                "isActive": true,
                "isTeamAdmin": false,
                "teamId": 1,
                "userId": 1,
                "user": {
                    "lastName": "Snow",
                    "isActive": true,
                    "id": 1,
                    "firstName": "Jon",
                    "isAdmin": false,
                    "lastUpdated": "2020-03-01 12:34:56",
                    "email": "dev@your.company",
                    "showWelcome": true
                }
            }
        ],
        "id": 1,
        "businessUnitId": 1,
        "businessUnit": {
            "description": "Modern Apps",
            "isActive": true,
            "id": 1,
            "name": "Modern Apps"
        },
        "lastUpdated": "2020-03-01 12:34:56",
        "name": "Developers"
    },

    "name": "test solution",
    "environments": [
        {
            "sharedVPCProjectId": "shared_vpc_host_project",
            "id": 1,
            "name": "Development"
        },
        {
            "sharedVPCProjectId": "shared_vpc_host_project",
            "id": 2,
            "name": "Production"
        }
    ],
    "cdId": 1,
    "deploymentFolderId": "MOCKFOLDERID3",
    "teamId": 1,
    "costCentre": "test",
    "isFavourite": false,
    "lastUpdated": "2020-08-18 09:19:13",
    "sourceControlId": 1
}
