### ISSUE TITLE
create solution rest api endpoint

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-gcp-dac#14]
Called by the houston service to initial a deployment, json payload to contain the solution to be deployed.

**Comment by karwootang-gft** [comment]
Add coded to handle the request from the houston service.

**Comment by karwootang-gft** [comment]
@sunderhill-gft - the changes are done can you review, feature/gcp-dac-14.
As discussed I haven't merged the changes into master, I'll let you do that.

**Comment by karwootang-gft** [comment]
Hi @sunderhill-gft Simon, The last line of solution.py is a test, needs to be removed when you merge to master.


successful_deployment_update(1)

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14
https://github.com/tranquilitybase-io/TranquilityBase/issues/18
