### ISSUE TITLE
Implement API method for creating a sandbox

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#152]
Implement DAC API methods to create a sandbox project, 

The sandbox project should have the following properties when built:
* the project is created in its own folder underneath the standard solution folder structure
* No network configured including no default network
* Assign the following roles on the project to the team's cloud identity group
  * roles/resourcemanager.projectIamAdmin 
  * roles/servicemanagement.quotaAdmin
  * roles/serviceusage.serviceUsageAdmin
* Apply the following labels to the project
  * cost-code
  * team
  * business-unit
  * environment
  * created-by
* The project name should follow naming conventions as closely as possible to enable readability and also to meet GCP naming rules.

**Comment by andy12838729** [comment]
Should we add Description as a Label ?

**Comment by sunhill** [comment]
Probably best not to add the description as a label. The length of a label value is a maximum 63 characters so if the description is lengthy then it would be truncated. Also have to be careful with characters as only following allowed for keys and values - 'Keys and values can contain only lowercase letters, numeric characters, underscores, and dashes.' Could have a field specifically for a label 'solution-description' which could be validated on the UI? I think there needs to be somewhere to define custom labels on the projects in addition to the mandatory ones.
