### ISSUE TITLE
Add gcp-dac container to eagle-console kubernetes cluster 

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#16]
Add gcp-dac container to eagle-console kubernetes cluster. Placeholder. TODO add issue in tb-gcp repo

**Comment by Salles-FA** [comment]
Issue related to:

- [Feature] Integrate Deploy Solutions with Houston and DaC Services https://github.com/tranquilitybase-io/tb-eagle-console/issues/64

**Comment by sunderhill-gft** [comment]
DAC added to Kubernetes Cluster in tb-gcp repo. See issue #255 in tb-gcp
