### ISSUE TITLE
Unit tests not working, no system tests run as part of the delivery pipeline 

### ISSUE THREAD

**Issue by geoff-gft** [tranquilitybase-io/tb-gcp-dac#184]
**Describe the bug**
When I push to source control unit and system tests are not run as part of the usual checks to allow merging 

**To Reproduce**
Push broken code to source control, observe no errors raised from github workflows
try to run unit tests, observe they have interpreter errors 
observe system tests are written for the mock but are not run automatically against the artifact image 

**Expected behavior**
I expect the CI system to reject code that fails unit or system tests

**Comment by sunderhill-gft** [comment]
There are tests in the DAC code base under gcp_tests. These are primarily integration tests as most of the meaningful testing on DAC needs a GCP environment to test against. These tests cannot currently be triggered on git checkin and expected to work until we have a permanent GCP test environment. There is a README file in the test directory that documents how to test locally against a DAC docker container.
For example the test_solution integration test creates and destroys a solution via the DAC API method.

**Comment by geoff-gft** [comment]
The task is specific about unit tests and system/functional tests, not integration.
