### ISSUE TITLE
Define Create Solution API function

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#2]
Define an API function to create a solution. Use Swagger.
The function will eventually create the solution container(s) required. See [here](https://github.com/tranquilitybase-io/tb-gcp-dac/wiki/DaC-Solution-Service)
Implement simple initial stub version that returns a json package.
Exact in/out parameters to be defined later.

Initial Parameters:
Solution ID
Solution Name
Returned:
Solution ID
Solution Name
Folder ID

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14
