### ISSUE TITLE
Deploy an activator within a solution via the Shared Services CD server

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#27]
Deploy an activator within a solution. The first activator to deploy should be the simple activator defined in the tb-activator-gft-base repository. 

The DaC instructs the centralised CD server in the Shared Services/DevOps folder to do the deployment. This is also how upgrades/changes are handled - with the DaC informing the central CD server.

Tasks associated with this issue:
#99 Done
#100 Done 
#101 Done
#102 Done
#111 Done
#113 Done
#122 Done
and also the following from tb-gcp:
#279 - Create Kubernetes Cluster with Jenkins hosted on to use for activator deployment pipeline **Done**
#380 - Configure DAC to speak to Jenkins **Done**
#345 - Define and create a Jenkinsfile to deploy an activator and also initiate a Jenkins worker(s)  **Done** for some activators

Onboarding an activator
#98 Done
#103 Done

<img width="1371" alt="Activator Deployment" src="https://user-images.githubusercontent.com/53095823/80263903-15593c80-868a-11ea-9337-74f4097313a4.png">

**Comment by andy12838729** [comment]
Have slightly amended this ticket to take into account the central CD server.
