### ISSUE TITLE
Create a project for each environment 

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#28]
Currently the dac is creating projects for DEV, STAGING and PRODUCTION when deploying a solution.
Change this so that projects are created for each environment passed in.
Look at implementing loops and conditionals in Terraform - [here](https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9) and [here](https://www.terraform.io/docs/configuration/expressions.html)

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/24
