### ISSUE TITLE
Connect solution projects to default shared VPC

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#32]
Connect each project created to the default shared VPC.

Initially there is only one shared VPC project that is passed in to the cluster (via ec-config.yaml).
In future it will be possible to add more shared VPCs for Dev, Prod etc.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/25

**Comment by sunderhill-gft** [comment]
Code in branch issue-32

**Comment by sunderhill-gft** [comment]
Current code in issue-32 branch successfully attaches the shared VPC to the projects created by the solution deployment
