### ISSUE TITLE
Send project details to Houston Service

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#33]
Return details of resources created when creating a resource.

The Houston Service will store this information in the Solution database. 

The information about the resources created by Terraform is stored in a storage bucket containing the Terraform state.

**Comment by Salles-FA** [comment]
Issue related to:

- [Feature] Integrate Deploy Solutions with Houston and DaC Services https://github.com/tranquilitybase-io/tb-eagle-console/issues/64

**Comment by sunderhill-gft** [comment]
Terraform state 'tf_state' returned using the 'terraform show' command - no need to access the bucket directly.

always returns 'status' when checking status of task.
also returns 'terraform_return_code' and 'tf_state' where appropriate.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/16
https://github.com/tranquilitybase-io/TranquilityBase/issues/19
https://github.com/tranquilitybase-io/TranquilityBase/issues/22
