### ISSUE TITLE
Allow same solution to be created and deleted many times

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#34]
Currently this can't be done with a solution as after an individual project is deleted it cannot be recreated again with the same project id. The deleted project still exists for some time after.
A possible solution is to add a random element to the created project id to make it always unique when it is created. NB project id cannot exceed 30 characters

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/118

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/191
