### ISSUE TITLE
Add background task manager

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#35]
Add a background task manager to the dac so that requests can be handled asynchronously. 

Suggested - use Celery/redis

Convert existing synchronous create solution method to run as a background task returning the task id.
Add another method for checking the current state of the task and returning the current state.

**Comment by sunderhill-gft** [comment]
Using Celery with Redis as a background task solution. This means adding redis and a worker node to the cluster.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/15
