### ISSUE TITLE
Review and Finalise the DevOps Shared Approach Architecture

### ISSUE THREAD

**Issue by aclement-gft** [tranquilitybase-io/tb-gcp-dac#38]
Review and finalise the Shared DevOps approach architecture based on the details mentioned in this issue
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/27

Defintion of Done: 

1.) Come up with a GitOps approach for deploying an solution/activator
2.) Define tasks required to implement the Architecture

**Comment by arvindclement** [comment]
Guys sorry I raised this issue in the wrong repository this can be closed this should have been under tb-gcp

**Comment by sunderhill-gft** [comment]
Closed as raised elsewhere
