### ISSUE TITLE
Automate build of docker container 

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#4]
Automate build of docker container on checkin to master. Package to be created and pushed to  gcr.io/tranquility-base-images/tb-gcp-dac.

Implement same functionality as exists currently in houston repo

**Comment by karwootang-gft** [comment]
Requirements
- build image and start container in a clean environment
- check at least able to access the rest api health endpoint then 
- can stay up for more than 10 seconds 
- built with tag CI in eagle-resources (Not auto-pushed to tranquilitybase images)
