### ISSUE TITLE
Add method for returning current status of deployment

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#43]
Return status of task upon querying with taskid. 
Initially support PENDING, STARTED, SUCCESS and FAILURE for create and delete solution.

The status will tie in with Celery's statuses for tasks
The default Celery states are:
* PENDING (waiting for execution or unknown task id)
* STARTED (task has been started)
* SUCCESS (task executed successfully)
* FAILURE (task execution resulted in exception)
* RETRY (task is being retried)
* REVOKED (task has been revoked)

**Comment by Salles-FA** [comment]
Related to this issue: 

- https://github.com/tranquilitybase-io/tb-houston-service/pull/168

**Comment by Salles-FA** [comment]
Issue related to:

- [Feature] Integrate Deploy Solutions with Houston and DaC Services https://github.com/tranquilitybase-io/tb-eagle-console/issues/64

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/15
https://github.com/tranquilitybase-io/TranquilityBase/issues/16
