### ISSUE TITLE
[Feature] Add Team, Created By User, Environment Labels

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-gcp-dac#44]
Add these 3 labels to the resources created when a Solution/Project is deployed

Also, business unit and cost centre

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/16
https://github.com/tranquilitybase-io/TranquilityBase/issues/17

**Comment by sunderhill-gft** [comment]
Envrionment label is already being applied. Created by User requires extra info from Houston - #313
