### ISSUE TITLE
Return key-value pairs instead of terraform state

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#62]
Currently the DAC returns the terraform state to the houston state as this contains the resource details required to send back to the houston service.
This was intended as an intermediate step.
The terraform state format will change as more functionality is added.
Move the terraform state processing currently in the houston service to the dac and return key-value pairs of the values required back to the houston service.
Will need to define response from create solution method in openapi.yaml

**Comment by karwootang-gft** [comment]
As discussed, we've been using the key "project-id-<env>", as a placeholder until the UI is ready to use the value.
