### ISSUE TITLE
Create folder structure

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#67]
Create additional folder structure underneath the root folder 'applications' if chosen in UI.

Folder structure will be specified in supplied JSON

Return folder ids of folders created as key/value pairs with the folder names.

Tasks:
* Add API methods to openapi.yml #68
* Implement methods in mock dac #69
* Implement methods in real dac, ensuring they can be run as Celery tasks #70
* Add deployment folder when creating a solution #77 
* Houston tasks: #209, #210

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/18
