### ISSUE TITLE
Add api method definitons for create folder structure

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#68]
Add api method definitions in openapi.yml for create folder .
Defined json structure to be sent to create folder method.

This will then be implemented later for the dac and the mock dac

Methods to be defined:
* Create folder 
* Create folder result
* Delete folder 
* Delete folder result
in same manner as defined for create solution

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/18
