### ISSUE TITLE
Implement WAN VPN - Create Deployment Workflow

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-gcp-dac#84]
Issue related to: tranquilitybase-io/TranquilityBase#31

Define endpoints for creating VPN in openapi.yml including input json
Add code for creating Celery task and calling terraform defined in #94

**Comment by sunderhill-gft** [comment]
Links to https://github.com/tranquilitybase-io/tb-gcp/issues/326
