### ISSUE TITLE
Terraform to create a VPN

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#94]
placeholder for [issue 326](https://github.com/tranquilitybase-io/tb-gcp/issues/326) in tb-gpc

Refs: https://cloud.google.com/community/tutorials/using-ha-vpn-with-aws
https://cloud.google.com/solutions/automated-network-deployment-multicloud
https://cloud.google.com/community/tutorials/deploy-ha-vpn-with-terraform

**Comment by sunderhill-gft** [comment]
Terraform code for this issue is in branch issue-326 of tb-gcp-dac

**Comment by Salles-FA** [comment]
related to https://github.com/tranquilitybase-io/tb-gcp/issues/391

**Comment by Salles-FA** [comment]
Issue related to: tranquilitybase-io/TranquilityBase#31
