### ISSUE TITLE
Initialize internal activator repo

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp-dac#98]
When an activator is imported via the Eagle console copy activator's repo into a Google Source Repository in the project ec-shared-xxx (where xxx is the landing zone discriminator)

**Comment by Salles-FA** [comment]
This issue is part of a Story in which the diagrams are described here:

 -  https://github.com/tranquilitybase-io/TranquilityBase/issues/47
